version: '3'
services:
  
  postgres:
    container_name: postgres
    build:
      context: Postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB_USERNAME=arg_value
        - POSTGRES_DB_PASSWORD=arg_value
    hostname: esa.postgres
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    container_name: redis
    build:
      context: Redis
      dockerfile: Dockerfile
    hostname: esa.redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
  
  edusurveyanalytics:
    container_name: edusurveyanalytics
    build:
      context: EduSurveyAnalytics
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB_USERNAME=arg_value
        - POSTGRES_DB_PASSWORD=arg_value
        - JWT_SECRET=arg_value
    image: banderveloper/edusurveyanalytics
    hostname: esa
    ports:
      - "5035:5035"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5035
    depends_on:
      - postgres
      - redis
    restart: on-failure

volumes:
  db_data: